In [68]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [69]:
df=pd.read_csv('/content/movies_metadata.csv')

In [70]:
df.sample(10)

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
27719,False,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",NaN,139808,tt1945034,es,Una pistola en cada mano,"A comedy centered on eight men in their 40s, a...",...,2012-12-05,0.0,100.0,"[{'iso_639_1': 'es', 'name': 'Español'}]",Released,NaN,A Gun in Each Hand,False,6.5,13.0
30203,False,NaN,0,"[{'id': 99, 'name': 'Documentary'}, {'id': 35,...",NaN,215646,tt2387601,en,The Special Need,28 year old Enea is looking for love - physica...,...,2013-01-23,0.0,84.0,"[{'iso_639_1': 'it', 'name': 'Italiano'}]",Released,NaN,The Special Need,False,4.5,2.0
15240,False,NaN,0,"[{'id': 99, 'name': 'Documentary'}]",NaN,92501,tt0372321,en,Hell's Highway: The True Story of Highway Safe...,This film covers the early history of post Wor...,...,2003-06-27,0.0,91.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Hell's Highway: The True Story of Highway Safe...,False,7.0,1.0
34812,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10402, 'n...",NaN,300666,tt2950052,en,Bravetown,"After an accidental drug overdose, a talented ...",...,2015-05-08,0.0,112.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Bravetown,False,6.5,87.0
31195,False,NaN,0,[],NaN,279086,tt0800199,en,Shoot the Messenger,Shoot the Messenger follows one man's painful...,...,2006-08-30,0.0,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Shoot the Messenger,False,6.0,1.0
25247,False,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 80, 'nam...",NaN,244458,tt1567437,en,The Voices,A mentally unhinged factory worker must decide...,...,2014-01-19,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Hearing voices can be murder.,The Voices,False,6.2,578.0
37227,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,85690,tt0329572,de,Scherbentanz,NaN,...,2002-10-31,0.0,0.0,"[{'iso_639_1': 'de', 'name': 'Deutsch'}]",Rumored,NaN,Shattered Glass,False,5.7,3.0
32021,False,NaN,0,"[{'id': 99, 'name': 'Documentary'}]",NaN,283317,tt3538766,es,Messi,"His teachers, coaches, childhood friends and B...",...,2014-09-06,0.0,93.0,"[{'iso_639_1': 'es', 'name': 'Español'}]",Released,NaN,Messi,False,7.7,49.0
21154,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,180050,tt0397696,ro,Un cartus de Kent și un pachet de cafea,"The father, fired two years before retirement,...",...,2004-02-05,0.0,15.0,"[{'iso_639_1': 'ro', 'name': 'Română'}]",Released,NaN,Cigarettes and Coffee,False,4.0,2.0
23269,False,NaN,0,"[{'id': 10749, 'name': 'Romance'}, {'id': 18, ...",NaN,130398,tt0031121,en,Broadway Serenade,Mary Hale (a singer) and Jimmy Seymour (pianis...,...,1939-04-07,0.0,114.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"It's got ""Maytime's"" glories...""Ziegfeld's"" th...",Broadway Serenade,False,0.0,0.0

In [71]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  object
 1   belongs_to_collection  4494 non-null   object
 2   budget                 45466 non-null  object
 3   genres                 45466 non-null  object
 4   homepage               7782 non-null   object
 5   id                     45466 non-null  object
 6   imdb_id                45449 non-null  object
 7   original_language      45455 non-null  object
 8   original_title         45466 non-null  object
 9   overview               44512 non-null  object
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  object
 12  production_companies   45463 non-null  object
 13  production_countries   45463 non-null  object
 14  release_date           45379 non-null  object
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(20)
memory usage: 8.3+ MB

In [72]:
missing_data = pd.DataFrame({
    'column_name': df.columns,
    'nulls_sum': df.isnull().sum(),
    'null_percentage': (df.isnull().sum() / len(df)) * 100
})

print(missing_data)

                                 column_name  nulls_sum  null_percentage
adult                                  adult          0         0.000000
belongs_to_collection  belongs_to_collection      40972        90.115691
budget                                budget          0         0.000000
genres                                genres          0         0.000000
homepage                            homepage      37684        82.883913
id                                        id          0         0.000000
imdb_id                              imdb_id         17         0.037391
original_language          original_language         11         0.024194
original_title                original_title          0         0.000000
overview                            overview        954         2.098271
popularity                        popularity          5         0.010997
poster_path                      poster_path        386         0.848986
production_companies    production_companies          3         0.006598
production_countries    production_countries          3         0.006598
release_date                    release_date         87         0.191352
revenue                              revenue          6         0.013197
runtime                              runtime        263         0.578454
spoken_languages            spoken_languages          6         0.013197
status                                status         87         0.191352
tagline                              tagline      25054        55.104914
title                                  title          6         0.013197
video                                  video          6         0.013197
vote_average                    vote_average          6         0.013197
vote_count                        vote_count          6         0.013197

In [73]:
df.shape

(45466, 24)

In [74]:
df=df.drop_duplicates().reset_index(drop=True)

In [75]:
df = df[['title', 'overview', 'genres','tagline','vote_average','popularity']]

In [76]:
df.isna().sum()

title               6
overview          954
genres              0
tagline         25045
vote_average        6
popularity          5
dtype: int64

In [77]:
df=df.dropna(subset=['title']).reset_index(drop=True)

In [78]:
df['overview']=df['overview'].fillna('')

In [79]:
df['genres'].iloc[0]

"[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]"

In [80]:
import ast
df['genres'] = df['genres'].apply(lambda x :" ".join([i['name'] for i in ast.literal_eval(x)]))

In [81]:
df.head()

,title,overview,genres,tagline,vote_average,popularity
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,NaN,7.7,21.946943
1,Jumanji,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,Roll the dice and unleash the excitement!,6.9,17.015539
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,6.5,11.7129
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,Friends are the people who let you be yourself...,6.1,3.859495
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,Just When His World Is Back To Normal... He's ...,5.7,8.387519

In [82]:
df['tagline']=df['tagline'].fillna('')

In [83]:
df.isna().sum()

title           0
overview        0
genres          0
tagline         0
vote_average    0
popularity      0
dtype: int64

In [84]:
df['tags']=df['overview'] + '' + df['genres'] + '' +df['tagline']

In [85]:
df.head()

,title,overview,genres,tagline,vote_average,popularity,tags
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,,7.7,21.946943,"Led by Woody, Andy's toys live happily in his ..."
1,Jumanji,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,Roll the dice and unleash the excitement!,6.9,17.015539,When siblings Judy and Peter discover an encha...
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,6.5,11.7129,A family wedding reignites the ancient feud be...
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,Friends are the people who let you be yourself...,6.1,3.859495,"Cheated on, mistreated and stepped on, the wom..."
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,Just When His World Is Back To Normal... He's ...,5.7,8.387519,Just when George Banks has recovered from his ...

In [86]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

In [87]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [88]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

In [89]:
def preprocess_text(text):
  #lowercase
  text = str(text).lower()
  #removed the punctuations
  text = re.sub(r'[^a-zA-Z\s]', '', text)

  words = text.split()
  #remove stopwords
  words = [word for word in words if word not in stop_words]

  #lemmatize
  words = [lemmatizer.lemmatize(word) for word in words]

  return " ".join(words)

In [90]:
df['tags'] = df['tags'].apply(preprocess_text)

In [92]:
df=df.reset_index(drop=True)

In [94]:
df.head()

,title,overview,genres,tagline,vote_average,popularity,tags
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,,7.7,21.946943,led woody andys toy live happily room andys bi...
1,Jumanji,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,Roll the dice and unleash the excitement!,6.9,17.015539,sibling judy peter discover enchanted board ga...
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,6.5,11.7129,family wedding reignites ancient feud nextdoor...
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,Friends are the people who let you be yourself...,6.1,3.859495,cheated mistreated stepped woman holding breat...
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,Just When His World Is Back To Normal... He's ...,5.7,8.387519,george bank recovered daughter wedding receive...

In [95]:
indices = pd.Series(df.index,index = df['title']).drop_duplicates()
indices

title
Toy Story                          0
Jumanji                            1
Grumpier Old Men                   2
Waiting to Exhale                  3
Father of the Bride Part II        4
                               ...
Subdue                         45442
Century of Birthing            45443
Betrayal                       45444
Satan Triumphant               45445
Queerama                       45446
Length: 45447, dtype: int64

In [96]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [97]:
tfidf = TfidfVectorizer(max_features=50000,ngram_range=(1,2),stop_words='english')

In [99]:
tfidf_matrix = tfidf.fit_transform(df['tags'])

In [100]:
tfidf_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1415680 stored elements and shape (45447, 50000)>

In [101]:
from sklearn.metrics.pairwise import cosine_similarity

In [102]:
def recommend(title, n = 10):
  if title not in indices:
    return ['Movie not found']

  idx = indices[title]
  sim_score = cosine_similarity(tfidf_matrix[idx], tfidf_matrix).flatten()
  similar_idx = sim_score.argsort()[::-1][1:n+1]
  return df['title'].iloc[similar_idx]

In [107]:
recommend('The Transporter',5)

6103                                   Ringu
18848                               Bullhead
39802               Johan Falk: Kodnamn Lisa
365      The Naked Gun 33⅓: The Final Insult
22524                                  Cargo
Name: title, dtype: object

In [108]:
import pickle

pickle.dump(tfidf_matrix,open('tfidf_matrix.pkl','wb'))

pickle.dump(indices,open('indices.pkl','wb'))

df.to_pickle('df.pkl')

pickle.dump(tfidf,open('tfidf.pkl','wb'))